---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: helloworld-deploy
spec:
    replicas: 2
    selector:
      matchLabels:
        app: helloworld-http
    template:
      metadata:
        labels:
          app: helloworld-http
      spec:
        containers:
        - name: helloworld-http
          image: strm/helloworld-http

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: helloworld-http

---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: hello-svc
    namespace: default
  spec:
    rules:
      - host: site.example.cloud
        http:
          paths:
            - backend:
                serviceName: helloworld-service
                servicePort: 80
    tls:
        - hosts:
            - site.example.cloud
          secretName: ingress-tls
